  
backend:
  name: github
  repo: icefire-project/icefire-web
  branch: main
  squash_merges: true
  api_root: https://api.github.com

media_folder: public/images/uploads
public_folder: /images/uploads

locale: es

collections:
  - name: pages
    label: Páginas
    folder: src/data/pages
    extension: json
    format: json
    create: true
    delete: false
    fields:
      - { label: Páginas, name: pages, widget: list, field: { label: Página, name: page, widget: object, fields: [
            { label: Slug, name: slug, widget: string },
            { label: Nombre, name: name, widget: string },
            { label: Tipo, name: type, widget: select, options: [page, group] },
            { label: Visible, name: visible, widget: boolean },
            { label: En Menú, name: inMenu, widget: boolean },
            { label: Orden, name: order, widget: number },
            { label: Descripción, name: description, widget: string },
            { label: Padre, name: parent, widget: string }
          ]} 
        }
